### ISSUE TITLE
Set up github CI for PRs

### ISSUE THREAD

**Issue by mistressofjellyfish** [mistressofjellyfish/not-grocy#10]
Since we now have a build system, I want to enforce some coding style standards.

In particular:

- standard for js
- php cs fixer

Unfortunately, php cs fixer absolutely hates working with blade views, but that isn't too much of a deal. I just need to figure out how to stop vscode to automatically try to fix blade-produced javascript in the view and/or finally move GrocyConfig to an API call.

**Comment by mohe2015** [comment]
Should I add new targets in the Makefile for the formatting and linting and then also run them in PR? Or do you already have these targets locally?

And what should I check: javascript formatting, php formatting, javascript linting, building, creating a release (maybe even automatically on tagging), running (probably should be tested when there are testst).

anything else?

**Comment by mohe2015** [comment]
Current state https://github.com/mohe2015/not-grocy/pull/1

**Comment by mistressofjellyfish** [comment]
Some are, some aren't.

Rollup runs eslint (in master for js, locally on my WIP stuff also for typescript and vue SFC). Currently, it just runs over everything and fixes what it can automatically on compile.

I'm unsure whether this is actually a good thing - eslint errors do not fail builds, so make doesn't catch that. If it's not too much of a hassle, I'd prefer to lint everything in a target so we can set it up as a pre-commit hook and just not bother with it during development (see https://levelup.gitconnected.com/how-to-run-eslint-using-pre-commit-hook-25984fbce17e?gi=dcf996dd53d2). Same goes for php, if the linter complains, don't commit, but fix your code (even if it just adds an ignore rule).

For now, I think the following is in scope:

- `make build`(no need to pack or minify, that just takes time),
- check formatting for javascript, php(, typescript, vue)
- (typecheck typescript)
- lint javascript
- running a development server `php -S localhost:8000 -t public`
- curl http://localhost:8000/api/stock doesn't error with 500 – conveniently, the demo data contains an API key, that makes this possible.

If it's easy to do, I would be more than grateful if some bootstrap work for phpunit would be included (even if there aren't any tests yet). Then I'll add vue-testing-library with my draft vue PR and we can work out how to integrate those tests into the CI best.

**Comment by mistressofjellyfish** [comment]
Re: PHP version – I'd be happy if we could also test on PHP 7.3 / node whatever version is in debian stable (unless there is an absolutely pressing issue not to do so – don't know about node).

I know that debian is often times referred to as a software museum, but I do run debian stable on basically all my production systems, because I don't have a hassle with it.

**Comment by mohe2015** [comment]
Your nice buddy the CI has found the following issue in the release make target - proposed fix:
```diff
diff --git a/Makefile b/Makefile
index cd6adaa1..600761ec 100644
--- a/Makefile
+++ b/Makefile
@@ -223,7 +223,7 @@ pack: publish manifest
                app.php \
                config-dist.php \
                grocy.openapi.json \
-               routes.php \
+               php/routes.php \
                version.json
 
 # this will error if the working tree is dirty (git diff-index will return a non-zero status code)
```

**Comment by mistressofjellyfish** [comment]
I will take a CI calling me an idiot any day. I'm currently knee-deep in vue stuff, feel free to send a PR, otherwise I'll fix that tomorrow.

**Comment by hackathi** [comment]
CI go brrr.
