### ISSUE TITLE
Bug: Uncaught Error: Call to a member function toJsonString() on null

### ISSUE THREAD

**Issue by mohe2015** [mistressofjellyfish/not-grocy#24]
With current master I get
```
<b>Fatal error</b>:  Uncaught Error: Call to a member function toJsonString() on null in /home/moritz/Documents/not-grocy/php/Services/LocalizationService.php:67
Stack trace:
#0 /home/moritz/Documents/not-grocy/php/Controllers/BaseController.php(140): Grocy\Services\LocalizationService-&gt;GetPoAsJsonString()
#1 /home/moritz/Documents/not-grocy/php/Controllers/BaseController.php(220): Grocy\Controllers\BaseController-&gt;render(Object(Slim\Http\ServerRequest), Object(Slim\Http\Response), 'errors/500', Array)
#2 /home/moritz/Documents/not-grocy/php/Controllers/ExceptionController.php(77): Grocy\Controllers\BaseController-&gt;renderPage(Object(Slim\Http\ServerRequest), Object(Slim\Http\Response), 'errors/500', Array)
#3 /home/moritz/Documents/not-grocy/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(127): Grocy\Controllers\ExceptionController-&gt;__invoke(Object(Slim\Http\ServerRequest), Object(UnexpectedValueException), true, false, false)
#4 /home/moritz/Documents/not-grocy/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(109): Slim in <b>/home/moritz/Documents/not-grocy/php/Services/LocalizationService.php</b> on line <b>67</b><br />

```
I don't really know why - maybe it's my system - maybe I'm stupid.
From a clean checkout with copying the config and setting dev mode and:
```
make build
make run
```

**Comment by mistressofjellyfish** [comment]
Yes, of course that's one of those errors that destroy the backtrace while they are at it. I'll look into!

**Comment by mohe2015** [comment]
```diff
diff --git a/php/Controllers/BaseController.php b/php/Controllers/BaseController.php
index 8a84b68c..8884fea4 100644
--- a/php/Controllers/BaseController.php
+++ b/php/Controllers/BaseController.php
@@ -135,7 +135,7 @@ class BaseController
                // only inclue strings loaded from the database on every request,
                // so that the rest can be cached and generated on build-time.
                // TODO: figure out why this is needed in the first place.
-               $dynamicLocalizationService = new LocalizationService($localizationService->Culture, true);
+               $dynamicLocalizationService = new LocalizationService($localizationService->Culture);
                $dynamicLocalizationService->LoadDynamicLocalizations();
                $this->View->set('GettextPo', $dynamicLocalizationService->GetPoAsJsonString());
```
would be the easiest fix that I found.

**Comment by mohe2015** [comment]
`FilesystemIterator::__construct(/home/moritz/Documents/not-grocy/php/Services/../migrations): failed to open dir: No such file or directory` is the root cause. So the migrations directory is missing.

**Comment by mohe2015** [comment]
```Error source:
```
/home/moritz/Documents/not-grocy/php/Services/DatabaseMigrationService.php:13
```

Error message:
```
FilesystemIterator::__construct(/home/moritz/Documents/not-grocy/php/Services/../migrations): failed to open dir: No such file or directory
```

Stack trace:
```
#0 /home/moritz/Documents/not-grocy/php/Services/DatabaseMigrationService.php(13): FilesystemIterator->__construct('/home/moritz/Do...')
#1 /home/moritz/Documents/not-grocy/php/Controllers/SystemController.php(27): Grocy\Services\DatabaseMigrationService->MigrateDatabase()
#2 /home/moritz/Documents/not-grocy/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(43): Grocy\Controllers\SystemController->Root(Object(Slim\Http\ServerRequest), Object(Slim\Http\Response), Array)
#3 /home/moritz/Documents/not-grocy/vendor/slim/slim/Slim/Routing/Route.php(384): Slim\Handlers\Strategies\RequestResponse->__invoke(Array, Object(Slim\Http\ServerRequest), Object(Slim\Http\Response), Array)
#4 /home/moritz/Documents/not-grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\Routing\Route->handle(Object(Slim\Http\ServerRequest))
#5 /home/moritz/Documents/not-grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\MiddlewareDispatcher->handle(Object(Slim\Http\ServerRequest))
#6 /home/moritz/Documents/not-grocy/vendor/slim/slim/Slim/Routing/Route.php(341): Slim\MiddlewareDispatcher->handle(Object(Slim\Http\ServerRequest))
#7 /home/moritz/Documents/not-grocy/vendor/slim/slim/Slim/Routing/RouteRunner.php(84): Slim\Routing\Route->run(Object(Slim\Http\ServerRequest))
#8 /home/moritz/Documents/not-grocy/php/Middleware/LocaleMiddleware.php(16): Slim\Routing\RouteRunner->handle(Object(Slim\Http\ServerRequest))
#9 /home/moritz/Documents/not-grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Grocy\Middleware\LocaleMiddleware->__invoke(Object(Slim\Http\ServerRequest), Object(Slim\Routing\RouteRunner))
#10 /home/moritz/Documents/not-grocy/php/Middleware/AuthMiddleware.php(31): class@anonymous->handle(Object(Slim\Http\ServerRequest))
#11 /home/moritz/Documents/not-grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Grocy\Middleware\AuthMiddleware->__invoke(Object(Slim\Http\ServerRequest), Object(class@anonymous))
#12 /home/moritz/Documents/not-grocy/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php(59): class@anonymous->handle(Object(Slim\Http\ServerRequest))
#13 /home/moritz/Documents/not-grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\RoutingMiddleware->process(Object(Slim\Http\ServerRequest), Object(class@anonymous))
#14 /home/moritz/Documents/not-grocy/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(107): class@anonymous->handle(Object(Slim\Http\ServerRequest))
#15 /home/moritz/Documents/not-grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\ErrorMiddleware->process(Object(Slim\Http\ServerRequest), Object(class@anonymous))
#16 /home/moritz/Documents/not-grocy/php/Middleware/CorsMiddleware.php(30): class@anonymous->handle(Object(Slim\Http\ServerRequest))
#17 /home/moritz/Documents/not-grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Grocy\Middleware\CorsMiddleware->__invoke(Object(Slim\Http\ServerRequest), Object(class@anonymous))
#18 /home/moritz/Documents/not-grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): class@anonymous->handle(Object(Slim\Http\ServerRequest))
#19 /home/moritz/Documents/not-grocy/vendor/slim/slim/Slim/App.php(215): Slim\MiddlewareDispatcher->handle(Object(Slim\Http\ServerRequest))
#20 /home/moritz/Documents/not-grocy/vendor/slim/slim/Slim/App.php(199): Slim\App->handle(Object(Slim\Http\ServerRequest))
#21 /home/moritz/Documents/not-grocy/php/app.php(94): Slim\App->run()
#22 /home/moritz/Documents/not-grocy/public/index.php(47): require_once('/home/moritz/Do...')
#23 {main}
```
			
```

**Comment by mistressofjellyfish** [comment]
Yes, there was a lurking path left from moving the files. I'll push a fix.

**Comment by mohe2015** [comment]
```diff
diff --git a/php/Services/DatabaseMigrationService.php b/php/Services/DatabaseMigrationService.php
index 8385d8e8..b906f30c 100644
--- a/php/Services/DatabaseMigrationService.php
+++ b/php/Services/DatabaseMigrationService.php
@@ -10,7 +10,7 @@ class DatabaseMigrationService extends BaseService
 
                $migrationFiles = [];
 
-               foreach (new \FilesystemIterator(__DIR__ . '/../migrations') as $file)
+               foreach (new \FilesystemIterator(__DIR__ . '/../Migrations') as $file)
                {
                        $migrationFiles[$file->getBasename()] = $file;
                }
```
is the fix for that. WIll send a PR if you weren't faster.

**Comment by mistressofjellyfish** [comment]
Fixed in 3f7273e.

**Comment by mohe2015** [comment]
```
make
...

Searching for localizations in /home/moritz/Documents/not-grocy/buildfiles/../localization/* \nGenerating cs...

Warning: Use of undefined constant REPO_BASE - assumed 'REPO_BASE' (this will throw an Error in a future version of PHP) in /home/moritz/Documents/not-grocy/php/Services/LocalizationService.php on line 102

Fatal error: Uncaught InvalidArgumentException: 'REPO_BASE/localization/cs/strings.po' is not a valid file in /home/moritz/Documents/not-grocy/vendor/gettext/gettext/src/Extractors/Extractor.php:37
Stack trace:
#0 /home/moritz/Documents/not-grocy/vendor/gettext/gettext/src/Extractors/Extractor.php(16): Gettext\Extractors\Extractor::getFiles('REPO_BASE/local...')
#1 [internal function]: Gettext\Extractors\Extractor::fromFile('REPO_BASE/local...', Object(Gettext\Translations), Array)
#2 /home/moritz/Documents/not-grocy/vendor/gettext/gettext/src/Translations.php(182): call_user_func('Gettext\\Extract...', 'REPO_BASE/local...', Object(Gettext\Translations), Array)
#3 [internal function]: Gettext\Translations->__call('addFromPoFile', Array)
#4 /home/moritz/Documents/not-grocy/vendor/gettext/gettext/src/Translations.php(161): call_user_func_array(Array, Array)
#5 /home/moritz/Documents/not-grocy/php/Services/LocalizationService.php(143): Gettext\Translations::__callStatic('fromPoFile', Array)
#6 /home/moritz/Documents/not-groc in /home/moritz/Documents/not-grocy/vendor/gettext/gettext/src/Extractors/Extractor.php on line 37
make: *** [Makefile:194: public/js/locales/grocy/en.json] Fehler 255
```
further fallout

**Comment by mohe2015** [comment]
(I can't reopen maybe this can be allowed somewhere)

**Comment by mistressofjellyfish** [comment]
> (I can't reopen maybe this can be allowed somewhere)

I'll setup an org tomorrow, then access control will be easier. I'll push a fix in a few.

**Comment by mistressofjellyfish** [comment]
generating locales works now.

The whole php stuff there is ultra fragile and sets up as little as possible to use the translation service that pulls what is not in database. Sorry about breaking it 😅 

This is just a reminder that we really, really, really need some automated CI testing set up, then this'll blow long before it's commited to master.

**Comment by mohe2015** [comment]
> This is just a reminder that we really, really, really need some automated CI testing set up, then this'll blow long before it's commited to master.

If you haven't started with it yet I could probably take care to create a CI script later this day. I assume you are fine with using Github Actions?

**Comment by mistressofjellyfish** [comment]
I have not and using Github Actions would be my preferred way of doing things. Your help is much appreciated, as always.
