### ISSUE TITLE
Move php source code to php/ directory

### ISSUE THREAD

**Issue by mistressofjellyfish** [mistressofjellyfish/not-grocy#8]
The project root is incredibly cluttered, and needs some cleanup. Proposed structure:

```
root
|- buildfiles
|- changelog
|- data
|- docs
|- js
|- localization
|- php
|- public
|- scss
|- (all non-php files currently in the project root)
```

Still not ideal, but what is.

**Comment by mohe2015** [comment]
In theory js and ts should be able to live in one directory. Also it could be discussed that the changelogs don't belong into the repository but into the github releases. But this is mostly personal taste.

**Comment by mohe2015** [comment]
Maybe the changelog directory could be moved into the docs directory? (for cleaning up the project root)

**Comment by mistressofjellyfish** [comment]
Hmmm, I think I'll leave that where it is right now. I'm not entirely sure how to keep track of everything (and I need to update it anyways), but what I do know is that docs/ doesn't really contain end-user documentation but developer stuff, so it won't get packed into the release zip.

The changelog directory does, and also the php code reads it. So (re-)moving that has further side effects.
